from tensorflow import keras
import tensorflow as tf
import os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

print("asd")

with tf.device('/cpu:0'):
    reconstructed_model = keras.models.load_model("my_h5_model.h5")

tryClass = [[55.0, 9.0, 9.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 25.0, 25.0]]

features = ['activities', 'providers', 'services', 'INTERNET', 'READ_PHONE_STATE', 'READ_EXTERNAL_STORAGE', 'WRITE_EXTERNAL_STORAGE', 'ACCESS_NETWORK_STATE',
            'BLUETOOTH', 'BLUETOOTH_ADMIN', 'ACCESS_COARSE_LOCATION', 'SYSTEM_ALERT_WINDOW', 'RECEIVE', 'BILLING', 'RECEIVE_BOOT_COMPLETED',
            'FOREGROUND_SERVICE', 'BIND_GET_INSTALL_REFERRER_SERVICE', 'VIBRATE', 'WAKE_LOCK', 'QUICKBOOT_POWERON', 'ACCESS_FINE_LOCATION',
            'SYSTEM_OVERLAY_WINDOW', 'CAMERA', 'ACCESS_WIFI_STATE', 'ACCESS_BACKGROUND_LOCATION', 'C2D_MESSAGE', 'MAPS_RECEIVE', 'READ_GSERVICES',
            'KILL_BACKGROUND_PROCESSES', 'BLUETOOTH_PRIVILEGED', 'FLASHLIGHT', 'CHANGE_WIFI_STATE', 'CALL_PHONE', 'GET_ACCOUNTS', 'READ_LOGS',
            'CHANGE_NETWORK_STATE', 'READ_PROFILE', 'REORDER_TASKS', 'DOWNLOAD_WITHOUT_NOTIFICATION', 'MOUNT_UNMOUNT_FILESYSTEMS', 'GET_TASKS',
            'CHANGE_WIFI_MULTICAST_STATE', 'REQUEST_INSTALL_PACKAGES', 'READ_CONTACTS', 'MANAGE_ACCOUNTS', 'AUTHENTICATE_ACCOUNTS',
            'ACCESS_NOTIFICATION_POLICY', 'UPDATE_BADGE', 'WRITE', 'READ', 'UPDATE_SHORTCUT', 'READ_SETTINGS', 'WRITE_SETTINGS', 'BROADCAST_BADGE',
            'BADGE_COUNT_WRITE', 'UPDATE_COUNT', 'READ_APP_BADGE', 'PROVIDER_INSERT_BADGE', 'CHANGE_BADGE', 'BADGE_COUNT_READ', 'CHECK_LICENSE',
            'ACCESS_LOCATION_EXTRA_COMMANDS', 'ACTIVITY_RECOGNITION', 'RECORD_AUDIO', 'NFC', 'MODIFY_AUDIO_SETTINGS', 'SEND_DOWNLOAD_COMPLETED_INTENTS',
            'INTERNAL_BROADCAST', 'NOTIFICATION', 'ACCESS_THIRD_PARTY_APP_AUTHORIZATION', 'READ_CARD_DATA', 'WRITE_CARD_DATA', 'USE_CREDENTIALS',
            'SET_WALLPAPER', 'REQUEST_IGNORE_BATTERY_OPTIMIZATIONS', 'READ_INTERNAL_STORAGE', 'WRITE_INTERNAL_STORAGE', 'PACKAGE_USAGE_STATS',
            'USE_FINGERPRINT', 'USE_BIOMETRIC', 'READ_CALENDAR', 'WRITE_USE_APP_FEATURE_SURVEY', 'OPPO_COMPONENT_SAFE', 'USE_COMPONENT', 'autofocus',
            'INSTALL_SHORTCUT', 'BIND_JOB_SERVICE', 'WRITE_SYNC_SETTINGS', 'EXPAND_STATUS_BAR', 'READ_SYNC_SETTINGS', 'MESSAGE', 'INTERACT_ACROSS_USERS_FULL',
            'SET_TIME_ZONE', 'WRITE_CALENDAR', 'ACCESS_GPS', 'ACCESS_LOCATION', 'CHANGE_CONFIGURATION', 'MEDIA_CONTENT_CONTROL', 'ACCESS_DOWNLOAD_MANAGER',
            'SET_ALARM', 'ACCESS_COARSE_UPDATES', 'TRANSMIT_IR', 'location', 'DISABLE_KEYGUARD', 'MIPUSH_RECEIVE', 'READ_PROVIDER', 'SET_WALLPAPER_HINTS',
            'REQUEST_DELETE_PACKAGES', 'WRITE_CONTACTS', 'CHANGE_APP_IDLE_STATE', 'ACTION_HEADSET_PLUG', 'bridge', 'BROADCAST_STICKY', 'RECORD_VIDEO',
            'STATUS_BAR', 'CONTROL_LOCATION_UPDATES', 'GET_PACKAGE_SIZE', 'CLEAR_APP_CACHE', 'gps', 'LOCATION', 'GET_COMMON_DATA', 'USE_FULL_SCREEN_INTENT',
            'WRITE_APN_SETTINGS', 'ACTION_MANAGE_OVERLAY_PERMISSION', 'ACCESS_MOCK_LOCATION', 'WRITE_MEDIA_STORAGE', 'YAHOO_INTER_APP', 'BROADCAST',
            'FB_APP_COMMUNICATION', 'iab', 'AUTH_SERVICE', 'READ_SYNC_STATS', 'STORAGE', 'WRITE_GSERVICES', 'SEND', 'BROADCAST_PACKAGE_CHANGED',
            'BROADCAST_PACKAGE_INSTALL', 'RESTART_PACKAGES', 'LOCATION_HARDWARE', 'BROADCAST_PACKAGE_REPLACED', 'BROADCAST_PACKAGE_ADDED',
            'ACCESS_FINGERPRINT_MANAGER', 'UA_DATA', 'UNINSTALL_SHORTCUT', 'BATTERY_STATS', 'ACCESS_PERMISSION', 'EXTENSION_PERMISSION', 'read_account_state',
            'WRITE_SECURE_SETTINGS', 'A4S_SEND', 'RECEIVE_ADM_MESSAGE', 'PROCESS_PUSH_MSG', 'PUSH_PROVIDER', 'READ_ATTACHMENT', 'ACCESS_ASSISTED_GPS',
            'RUN_INSTRUMENTATION', 'CUSTOMER_ATTRIBUTE_SERVICE', 'COLLECT_METRICS', 'changed', 'CAN_CALL_MAP_INFORMATION_PROVIDER',
            'CALL_AMAZON_DEVICE_INFORMATION_PROVIDER', 'GENERIC_IPC', 'METRICS_PERMISSION', 'MANAGE_COR_PFM', 'AUTH_SDK', 'USE_DEVICE_CREDENTIALS',
            'READ_PRELOAD_DEVICE_INFO_PROVIDER', 'DYN_CONFIG_VALUES_UPDATED', 'ACCESS_PROVIDER', 'SET_TIME', 'INTERACT_ACROSS_USERS', 'READ_DATABASE',
            'Permission', 'SEND_SMS', 'READ_SMS', 'permission', 'RECEIVE_SMS', 'GOOGLE_PHOTOS', 'RECEIVE_USER_PRESENT', 'BIND_NOTIFICATION_LISTENER_SERVICE',
            'ACCESSORY_FRAMEWORK', 'DELETE_PACKAGES', 'STATUS_BAR_SERVICE', 'READ_DATA', 'READ_HISTORY_BOOKMARKS', 'REAL_GET_TASKS', 'WRITE_CALL_LOG',
            'ACCESS_SERVICE', 'WRITE_SMS', 'INSTALL_PACKAGES', 'INTERNAL_SYSTEM_WINDOW', 'RECEIVE_WAP_PUSH', 'DEVICE_POWER', 'FORCE_STOP_PACKAGES',
            'RECEIVE_MMS', 'READ_PERMISSION', 'BACKUP_RESTORE', 'SOFT_RESET', 'READ_CALL_LOG', 'WRITE_DATABASE', 'INJECT_EVENTS', 'COM_WSSNPS', 'LOG',
            'READ_PRIVILEGED_PHONE_STATE', 'CONTENT_PROVIDER', 'USE_ALML', 'GET_INTENT_SENDER_INTENT', 'USB_PERMISSION', 'RECIEVE_MCS_MESSAGE', 'SET_DEBUG_APP',
            'CAPTURE_VIDEO_OUTPUT', 'FLAG_GRANT_READ_URI_PERMISSION', 'MANAGE_DOCUMENTS', 'PERMISSION_RUN_TASKS', 'USE_SIP', 'CONFIGURE_SIP', 'JPUSH_MESSAGE',
            'Unnamed: 229', 'PushHandlerActivity', 'BIND_APPWIDGET', 'PUSHIO_MESSAGE', 'WRITE_HISTORY_BOOKMARKS', 'CALL_PRIVILEGED',
            'START_ACTIVITIES_FROM_BACKGROUND', 'LOCAL_MAC_ADDRESS', 'REGISTER', 'PLUGIN', 'BIND_ACCESSIBILITY_SERVICE', 'READ_CONTENT_PROVIDER',
            'GALLERY_PROVIDER', 'STOP_APP_SWITCHES', 'ANSWER_PHONE_CALLS', 'QSB', 'ACCESS_WEATHERCLOCK_PROVIDER', 'RECEIVE_LAUNCH_BROADCASTS', 'READ_MESSAGES',
            'PROVIDER', 'LAUNCH_PERSONAL_PAGE_SERVICE', 'MANAGE_USERS', 'UPDATE_APP_OPS_STATS', 'READ_SOCIAL_STREAM', 'ACCESS_ALL_DOWNLOADS', 'ACCESS',
            'GET_ACCOUNTS_PRIVILEGED', 'ACCESS_SUPERUSER', 'BIND_WALLPAPER', 'SUBSCRIBED_FEEDS_WRITE', 'SUBSCRIBED_FEEDS_READ', 'READ_EPG_DATA',
            'WRITE_EPG_DATA', 'ACCESS_MEDIA_LOCATION', 'PAY_THROUGH_BAZAAR', 'MANAGE_OVERLAY_PERMISSION', 'READ_USER_DICTIONARY', 'WRITE_USER_DICTIONARY',
            'CHANGE_COMPONENT_ENABLED_STATE', 'RAISED_THREAD_PRIORITY', 'MODIFY_PHONE_STATE', 'UPDATE_DEVICE_STATS', 'PROVIDE_BACKGROUND',
            'provider', 'ACCESS_SURFACE_FLINGER', 'RECEIVE_COMPLICATION_DATA', 'Companion', 'HW_SIGNATURE_OR_SYSTEM', 'SYSTEM_UI_VISIBILITY_EXTENSION',
            'ACCESS_LAUNCHER_DATA', 'SET_WALLPAPER_COMPONENT', 'WRITE_PROFILE', 'ENABLE_NOTIFICATION', 'MOUNT_FORMAT_FILESYSTEMS', 'CLEAR_APP_USER_DATA',
            'READ_GMAIL', 'DUMP', 'READ_OWNER_DATA', 'CAPTURE_SECURE_VIDEO_OUTPUT', 'CAPTURE_AUDIO_OUTPUT', 'READ_FRAME_BUFFER', 'jotspot', 'adsense',
            'READ_WRITE_ALL_VOICEMAIL', 'news', 'ADD_VOICEMAIL', 'HW_ACCESS_AUTH_SERVICE', 'gbase', 'OTHER_SERVICES', 'BODY_SENSORS', 'GOOGLE_AUTH',
            'WRITE_RECORD_AUDIO', 'WRITE_OWNER_DATA', 'WRITE_SOCIAL_STREAM', 'mail', 'READ_ONLY', 'notebook', 'blogger', 'speechpersonalization', 'lh2',
            'adwords', 'print', 'sitemaps', 'groups2', 'grandcentral', 'finance', 'ah', 'GET_CLIPS', 'writely', 'CHANGE_WIMAX_STATE', 'Controller', 'wise',
            'orkut', 'ACCESS_WIMAX_STATE', 'AD_ID_NOTIFICATION', 'cp', 'health', 'BIND_DIRECTORY_SEARCH', 'read', 'VOIP_INTERFACE', 'ACCESS_CACHE_FILESYSTEM',
            'READ_INSTALL_SESSIONS', 'READ_CELL_BROADCASTS', 'PERSISTENT_ACTIVITY', 'wifi', 'youtube', 'WRITE_CLIPS', 'talk', 'dodgeball', 'mobile',
            'READ_CLIPS', 'WRITE_ONLY', 'ACCOUNT_MANAGER', 'READ_MSG_PREF', 'READ_RECORD_AUDIO', 'ig', 'speech', 'write', 'cl', 'knol', 'local', 'YouTubeUser',
            'BOOT_COMPLETED', 'ACCESS_DOWNLOAD_MANAGER_ADVANCED', 'PROCESS_OUTGOING_CALLS', 'CONNECTIVITY_CHANGE', 'DELETE_CACHE_FILES',
            'SET_PREFERRED_APPLICATIONS', 'OVERRIDE_WIFI_CONFIG', 'CONNECTIVITY_INTERNAL', 'REBOOT', 'MANAGE_OWN_CALLS',
            'REQUEST_COMPANION_USE_DATA_IN_BACKGROUND', 'READ_PHONE_NUMBERS', 'REQUEST_COMPANION_RUN_IN_BACKGROUND', 'READ_NETWORK_USAGE_HISTORY',
            'IDS_PERMISSION', 'PERMISSION', 'FIDO_CLIENT', 'NETWORK', 'PRIVATE', 'PAYMENT_BROADCAST_PERMISSION', 'REGISTRATION', 'PHONE_STATE',
            'GPS_ENABLED_CHANGE', 'ACCESS_MODULE_API', 'SET_ORIENTATION', 'camera', 'flash', 'ACCESS_COURSE_LOCATION', 'BADGE_ICON', 'LAYER_PUSH',
            'CAMERA_ADDON', 'ACCESS_DATA', 'ACCESS_CORSE_LOCATION', 'DECODE', 'EMDK', 'BROADCAST_PACKAGE_REMOVED', 'MDM_APP_MGMT', 'CAMERA2',
            'PermissionRequest', 'SMALLAPP', 'PROCESS_INCOMING_CALLS', 'DIAL_PHONE', 'ACCESS_CHECKIN_PROPERTIES', 'ALL_SERVICES', 'SMARTCARD',
            'PREVENT_POWER_KEY', 'ACCESS_NOTIFICATIONS', 'MEDIA_MOUNTED', 'RECEIVE_FIRST_LOAD_BROADCAST', 'ALLSHARE_CAST_SERVICE', 'SET_PROCESS_LIMIT',
            'READ_CREDENTIALS', 'AM_COMMUNICATION', 'ACCESS_ACCOUNT', 'INSTALL_LOCATION_PROVIDER', 'READ_WRITE_BOOKMARK_FOLDERS', 'accelerometer', 'MICROPHONE',
            'BIND_WIDGET', 'TOS_ACKED', 'DEVICE_EXTRAS', 'READ_TASKS', 'READ_EXTENSION_DATA', 'PHONE_STATE_STATE', 'BROADCAST_RECEIVER',
            'ACCESS_BACKGROUND_SERVICE', 'PER_ACCOUNT_TYPE', 'USE_SOCIALSERVICE', 'PUSH', 'activate', 'MAIN', 'LAUNCHER', 'MY_PACKAGE_REPLACED',
            'USB_DEVICE_ATTACHED', 'USB_DEVICE_DETACHED', 'BOOT_COMPLETED.1', 'QUICKBOOT_POWERON.1', 'INSTALL_REFERRER', 'RECEIVE.1', 'APPWIDGET_UPDATE',
            'PACKAGE_REPLACED', 'INSTANCE_ID_EVENT', 'MESSAGING_EVENT', 'DEFAULT', 'empty', 'data', 'VIEW', 'BROWSABLE', 'ACTION_SHUTDOWN', 'TIMEZONE_CHANGED',
            'WAKE_FOR_ALARM', 'ACTION_CURRENT_ACCESS_TOKEN_CHANGED', 'AccountAuthenticator', 'APPWIDGET_CONFIGURE', 'INTERCOM_PUSH_OPENED',
            'INTERCOM_PUSH_DISMISSED', 'ACTION_POWER_CONNECTED', 'ACTION_POWER_DISCONNECTED', 'BATTERY_OKAY', 'BATTERY_LOW', 'DEVICE_STORAGE_LOW',
            'DEVICE_STORAGE_OK', 'CONNECTIVITY_CHANGE.1', 'TIME_SET', 'UpdateProxies', 'ACL_CONNECTED', 'startservice', 'service', 'EDIT', 'ACTION_PREVIEW',
            'BACKGROUND_FETCH', 'FLUTTER_NOTIFICATION_CLICK', 'REGISTRATION.1', 'MESSAGE_RECEIVED', 'NOTIFICATION_RECEIVED', 'NOTIFICATION_OPENED',
            'CONNECTION', 'RECEIVE_MESSAGE', 'action', 'client', 'ACTION_BOOT_COMPLETED', 'NotificationExtender', 'CARDBOARD', 'direction_clicked',
            'delete_interactive_broadcast', 'delete_seperate_gif_broadcast', 'gif_play_clicked', 'gif_play_service', 'GETUDID', 'STATE_CHANGE',
            'DOWNLOAD_COMPLETE', 'support', 'SEARCH_ACTION', 'SEARCH', 'android', 'ACTION_TASK_READY', 'APPWIDGET_DELETED', 'APPWIDGET_ENABLED',
            'APPWIDGET_DISABLED', 'NDEF_DISCOVERED', 'SCREEN_ON', 'CARD_UPDATE', 'CARD_EVENT', 'CARD_ENABLED', 'CARD_DISABLED', 'ACTION_EXECUTE', 'store',
            'save_preference', 'start_battery_service', 'save_main_preference', 'start_main_battery_service', 'widget', 'PACKAGE_ADDED', 'PACKAGE_REMOVED',
            'APPWIDGET_UPDATE_OPTIONS', 'APPWIDGET_RESTORED', 'switch_forest_type', 'apply_for_amber', 'download_amber', 'more_skin', 'weather_warning_cancel',
            'weather_warning_click', 'weather_condition_click', 'weather_condition_cancel', 'temp_change_push_click', 'aqi_click', 'aqi_cancel',
            'PHONE_STATE.1', 'NEW_OUTGOING_CALL', 'ALARM_ALERT', 'ALARM_DONE', 'INNER_ACTION', 'USER_PRESENT', 'TIME_TICK', 'WallpaperService', 'aidl',
            'NotificationListenerService', 'v3', 'LeanplumPushFirebaseMessagingService', 'PUSH_EVENT', 'BG_EVENT', 'ACTION_REFRESH', 'STATE_CHANGED',
            'ACTION_FOUND', 'NOTIFICATION.1', 'SEND.1', 'DATA_CHANGED', 'RESUME_CHAT', 'RUN_JOB', 'ACTION_UPDATE_TIME', 'WIFI_STATE_CHANGED',
            'locationUpdateKey', 'BROADCAST.1', 'ACL_DISCONNECTED', 'NEW_PICTURE', 'DELETE', 'OPEN', 'CHANNEL_EVENT', 'category.1', 'WEEX', 'MEDIA_MOUNTED.1',
            'MEDIA_UNMOUNTED', 'SCREEN_OFF', 'SyncAdapter', 'bindingx', 'binding', 'expressionBinding', 'webview', 'picturepagerview', 'openfile',
            'DEVICE_ADMIN_ENABLED', 'DEVICE_ADMIN_DISABLED', 'MESSAGE_ARRIVED', 'MI_MESSAGE_ARRIVED', 'MESSAGE_CLICKED', 'MI_MESSAGE_CLICKED',
            'THIRD_PARTY_PUSH_STATE', 'HEART_BEAT', 'RECEIVED', 'GEOFENCE_TRANSITIONED', 'LOCATIONS_RECEIVED', 'PROVIDERS_CHANGED', 'ANALYTICS_DISPATCH',
            'SAID_CHANGED', 'REQUEST_DIAGNOSTICS', 'LEANBACK_LAUNCHER', 'ACTION_NONE', 'DAYDREAM', 'ALARM', 'DATE_CHANGED', 'LOCALE_CHANGED',
            'ACTION_APPWIDGET_DISABLED', 'ACTION_APPWIDGET_DELETED', 'NOTIFICATION_REMOVED', 'COMMAND', 'ERROR', 'PUSH.1', 'PUSH_STATE', 'SERVICE', 'PING_V4',
            'taobao', 'NOTIFY_ACTION', 'MessageReceiverService', 'NEXT_ALARM_CLOCK_CHANGED', 'SMS_RETRIEVED', 'PUSH_CLICKED', 'PUSH_DEEPLINK_CLICKED',
            'PUSH_URL_CLICKED', 'DFU_UPLOAD', 'NOTIFICATION_ACTION', 'APP_BLOCK_STATE_CHANGED', 'NOTIFICATION_CHANNEL_BLOCK_STATE_CHANGED',
            'NOTIFICATION_CHANNEL_GROUP_BLOCK_STATE_CHANGED', 'IMetricaService', 'ACTION_INIT', 'START_SERVICE', 'HOME', 'LOCKED_BOOT_COMPLETED',
            'CARRIER_CONFIG_CHANGED', 'EVENT_REMINDER', 'USB_ACCESSORY_DETACHED', 'PACKAGE_FULLY_REMOVED', 'BIND_LISTENER', 'SCAN', 'CAR_DOCK', 'CAR_MODE',
            'MEDIA_BUTTON', 'AUDIO_BECOMING_NOISY', 'VOLUME_CHANGED_ACTION', 'MediaBrowserService', 'alarmreciever', 'Download_Cancelled', 'Download_Play',
            'Download_Pause', 'REBOOT.1', 'PLC', 'TECH_DISCOVERED', 'PAIRING_REQUEST', 'BOND_STATE_CHANGED', 'FOUND', 'bridge.1', 'QS_TILE', 'main', 'rootview',
            'setting', 'Data', 'WeatherUnit', 'SDKConfig', 'id', 'NOTIFY', 'ADAPTER_STATE_CHANGED', 'GET_CONTENT', 'OPENABLE', 'PREFS', 'click_nothing',
            'cancel_notification', 'Extension', 'MULTIWINDOW_LAUNCHER', 'MapService', 'event', 'IServiceImpl', 'InstanceID', 'NOTIFICATION_PREFERENCES',
            'ASSIST', 'mobile.1', 'ACTION_START', 'WEB_VIEW', 'NOTIFICATION_CANCELLED', 'SEND_MULTIPLE', 'DESK_DOCK', 'VIDEO', 'DOCK_EVENT', 'ENTER_CAR_MODE',
            'EXIT_CAR_MODE', 'QUICKBOOT_POWEROFF', 'FORCED_APPWIDGET_UPDATE', 'APPWIDGET_THEME_CHANGED', 'APPWIDGET_UPDATE_PERIOD_CHANGED', 'UPLOAD',
            'SYSAPP_RECOMMEND', 'INTERNAL_NAVIGATION', 'msg_push_click', 'START_FROM_AGOO', 'OrangeApiService', 'IRemoteNetworkGetter', 'IXState',
            'FaceDetectorService', 'video', 'ACTION_PROCESS_UPDATES', 'REFRSH', 'yes', 'no', 'cookie', 'optin_message', 'SHORTCUT', 'ACTION_WIDGET_CLICK',
            'SIM_STATE_CHANGED', 'AIRPLANE_MODE', 'IN_APP_PURCHASES_CHANGED', 'SETUP', 'RELOAD', 'START_APP', 'refresh', 'changed.1', 'update', 'PUSH_ACTION',
            'MODE_CHANGED', 'WIDGET_CONTROL', 'CLOCK_TICK', 'JOB_CLOCK_TICK', 'RESTART_SERVICE', 'BATTERY_CHANGED', 'UPDATE', 'APPBOY_PUSH_RECEIVED',
            'APPBOY_NOTIFICATION_OPENED', 'ARCHIVE', 'ACTION_PICK', 'ACTION_MULTIPLE_PICK', 'REFRESH', 'PREFERENCE', 'SHOW_RATE_APP_INTENT_ACTION',
            'APPWIDGET_OPTIONS_CHANGED', 'OPENED', 'widget_action_start_app', 'widget_action_ui_update', 'widget_action_grid_click', 'udp', 'tuya', 'fcm',
            'notify', 'click', 'detail', 'check', 'debug', 'driver', 'HomeActivity', 'PROFILE', 'REVIEW', 'MESSAGE.1', 'LOGIN', 'FIDO_OPERATION',
            'CATEGORY_PROJECTION', 'start', 'PUSH_DELAY_NOTIFY', 'ELECTION', 'DOWNLOAD_NOTIFICATION_CLICKED', 'SplashActivity', 'share', 'user',
            'ACTION_VIEW_DOWNLOADS', 'HEADSET_PLUG', 'CONNECTIVITY_ACTION', 'INSERT', 'APPWIDGET_RESIZE', 'FCM_PLUGIN_ACTIVITY', 'START', 'PACKAGE_INSTALL',
            'CHECK_SERVICE', 'SHOW_LANDING_PAGE_INTENT_ACTION', 'ACTION_SDK_REQ_ACTIVITY', 'ACTION_SDK_REQ_STORY', 'ACTION_REFRESH_WXAPP', 'CHANNEL_UPDATED',
            'DISMISSED', 'MEDIA_EJECT', 'OPEN_ACTIVITY_1', 'easyapp', 'DATA_FETCHED', 'MainActivity', 'POWER_SAVE_MODE_CHANGED', 'PACKAGE_RESTARTED',
            'ENABLE_WALLET_OPTIMIZATION', 'cancel', 'APP_LAUNCH', 'TERMINATE', 'LAUNCH', 'PROVIDER_CHANGED', 'ADDON', 'dashboard', 'BIND', 'settings',
            'Playvideo', 'EMBED', 'BeaconPeriodicTasksBroadcastReceiver', 'STOP_SCAN', 'SYNC', 'SMS_RECEIVED', 'deeplinking', 'app', 'MONKEY',
            'EXTENSION_REGISTER_REQUEST', 'ACCESSORY_CONNECTION', 'VIEW_EVENT_DETAIL', 'REFRESH_REQUEST', 'START_REFRESH_IMAGE_REQUEST',
            'STOP_REFRESH_IMAGE_REQUEST', 'ONTOUCH', 'STOP', 'PAUSE', 'RESUME', 'KEY_EVENT', 'TOUCH_EVENT', 'SWIPE_EVENT', 'UpdateWidget',
            'UpdateAndCheckServer', 'CreateWidget', 'INTENT_ACTION_BEACON_NOTI', 'ACTION', 'UPDATE_WIDGET', 'send', 'action_navigate', 'AccessibilityService',
            'WALLPAPER_CHANGED', 'success', 'NETWORK_STATE_CHANGED_ACTION', 'need', 'CLICKED', 'PUSH_NOTIFICATIONS', 'QUERY', 'ANONYM_ID', 'CLICK',
            'venteprivee', 'DISMISS', 'LOCAL_NOTIF', 'NOTIFY_MSG', 'PASSBY_MSG', 'NOTIFICATION_TAPPED', 'NOTIFICATION_DISMISSED', 'alarm', 'work',
            'ACTION_DUMP_PREFERENCE', 'weather', 'CANCEL_JOB_ALARM_SUB', 'VIEW_RICH_PUSH_INBOX', 'VIEW_RICH_PUSH_MESSAGE', 'BOOTSTRAP_SSO', 'SYNC_DIRTY_DATA',
            'CLEAN_DATA', 'LOCATE', 'SETTINGS_UPDATED', 'SERVICE_STATE', 'SyncService', 'TAG_DISCOVERED', 'pay', 'PENWINDOW_LAUNCHER', 'PLAY', 'SKIP', 'REWIND',
            'ACTION_USER_PRESENT', 'error', 'WEB_SEARCH', 'GetCredential', 'shopping', 'added', 'removed', 'MEDIA_SCANNER_FINISHED', 'NEW_VIDEO',
            'CLRemoteService', 'VIEW_DEEP_LINK', 'cars', 'download', 'Home', 'DISPLAY_NOTIFICATION', 'ACTION_UPDATE', 'LOGIN_ACCOUNTS_CHANGED',
            'INITIATE_NAVIGATION', 'USB_ACCESSORY_ATTACHED', 'IRemoteService', 'messenger', 'HOST_APDU_SERVICE', 'DIAL', 'VOICE_COMMAND',
            'VOICE_SEARCH_HANDS_FREE', 'SERVICE_CONNECTION_REQUESTED', 'ACCESSORY_SERVICE_CONNECTION_IND', 'REGISTER_AFTER_INSTALL', 'CONNECTION_STATE_CHANGED',
            'InCallService', '2', 'APPBOY_PUSH_DELETED', 'ACTION_WIDGET_RECEIVER', 'TPUSH', 'PUSH_ALARM', 'new', 'open', 'INAPP_NOTIFICATIONS', 'TRANSITION',
            'PREFERENCES', 'stop', 'NOTIFIER', 'START_ACTIVITY', 'gcm', 'USER_INITIALIZE', 'ACCOUNT_REMOVED', 'PACKAGE_DATA_CLEARED', 'DEVICE_OWNER_CHANGED',
            'MEDIA_NOFS', 'MEDIA_REMOVED', 'MEDIA_SCANNER_SCAN_FILE', 'MEDIA_SCANNER_STARTED', 'MEDIA_UNMOUNTABLE', 'WAP_PUSH_RECEIVED', 'sync', 'exit',
            'CONNECTION_CHANGE', 'PUSH_MESSAGE', 'FEEDBACK', 'PING_TIMER', 'SDK', 'INTERNAL_PUSH_MESSAGE', 'MEDIA_CHECKING', 'RECEIVE_MCS_MESSAGE',
            'MOB_GUARD_SERVICE', 'activity_action', 'receive', 'IN_APP_NOTIFY', 'RESPONSE_CODE', 'PURCHASE_STATE_CHANGED', 'VpnService', 'club', 'APP_MAPS',
            'api_request', 'USB_STATE', 'me', 'SILENT_PUSH_RECEIVE', 'IS_DATA_COLLECTOR', 'INTENSIVE_DATA_TRANSFER_ON', 'INTENSIVE_DATA_TRANSFER_OFF',
            'OPEN_CRAFT_ITEM', 'OPEN_SEARCH_RESULTS', 'ACTION_REQUESTED_AT', 'ACTION_LOGOUT', 'ACTION_RECEIVE_AT', 'ACTION_CLEANUP_SCREENSHOTS',
            'NOTIFICATION_DINNER', 'NOTIFICATION_DINNER_CANCEL', 'NOTIFICATION_DAILY_DIGEST', 'NOTIFICATION_DAILY_DIGEST_CANCEL', 'NOTIFICATION_WEEKLY_DIGEST',
            'NOTIFICATION_WEEKLY_DIGEST_CANCEL', 'UPDATE_INDEX', 'DISABLED', 'PROCESS_UPDATES', 'ACTION_TOGGLE_PLAY', 'ACTION_PLAY', 'ACTION_PAUSE',
            'ACTION_STOP', 'ACTION_SET_URL', 'ACTION_REWIND', 'ACTION_FAST_FORWARD', 'ACTION_STOP_DOWNLOADS', 'webaty', 'aty', 'search', 'activity',
            'ACTION_RECEIVE_GEOFENCE', 'HOVER', 'CREATE_SHORTCUT', 'EDIT_SETTING', 'OBJECT_CLICK_EVENT', 'MENU_ITEM_SELECTED', 'FIRE_SETTING', 'INFO',
            'google_flip_intent', 'ACTION_PACKAGE_REPLACED', 'QUERY_PACKAGE_RESTART', 'LAUNCH_INVITE', 'LAUNCH_SURVEY', 'OPEN_DOCUMENT', 'PICK', 'ALTERNATIVE',
            'NOTIFICATION_CHECK', 'APPLICATION_PREFERENCES', 'proximity_trigger', 'DEVICE_ADMIN_DISABLE_REQUESTED', 'home', 'PushActivity', 'tracker',
            'NOTIFICATION_RECEIVED_PROXY', 'REGISTER.1', 'REPORT', 'PushService', 'PUSH_TIME', 'DaemonService', 'SMS_RETRIEVE', 'ACTION_GEOFENCING_SERVICE',
            'COCKTAIL_UPDATE', 'NOTIFICATIONPRESSED', 'APP_BROWSER', 'INCOGNITO', 'BOOKMARK', 'ACTION_TIME_CHANGED', 'EXTERNAL_APPLICATIONS_AVAILABLE',
            'CHECK_SUBSCRIPTION', 'SDK_LICENSE', 'remote', 'REGISTER_KIT', 'DreamService', 'babychakra', 'gcmquickstart', 'CLOSE', 'SETTINGS', 'IA_SETTINGS',
            'UUID', 'MEDIA_PLAY_FROM_SEARCH', 'RESTART', 'SwrveWakeful', 'SubscriptionActivity', 'CANCEL_NOTIFICATION', 'FilterNotifications', 'notification',
            'receiver', 'WEATHER_UPDATED', 'LOCATION_UPDATED', 'hybrid', 'connect', 'disconnect', 'change',
            'command', 'PROCESS_TEXT', 'NOTIFICATION_DELETED', 'ADD_PROMO', 'ADD_PREVIEW_PROMO', 'LOG_DEBUG_DATA', 'CLEAR_COUNTERS', 'FETCH_PROMOTIONS',
            'FETCH_EVAL_RESULTS', 'marketplace', 'ACTION_PERMIT', 'ACTION_BLOCK', 'REFRESH_GEOFENCES', 'ACTION_PUSH_ACTION', 'BUTTON', 'PREV', 'NEXT', 'ITEM',
            'SHOWN', 'HANDLE_CUSTOM_EVENT', 'UMS_CONNECTED', 'PACKAGE_CHANGED', 'ENABLE', 'DISABLE', 'prev', 'next', 'play', 'pause', 'ACTION_USER_LOGGED_OUT',
            'ACTION_NOTIFICATION_CLICKED', 'ACTION_BIND', 'backup', 'InputMethod', 'upload', 'flow', 'config', 'network', 'close', 'info', 'get', 'response',
            'Unnamed: 1050', 'BEACON_SERVICE_STARTED', 'LAUNCHER_APP', 'CONFIRM_PIN_SHORTCUT', 'CONFIRM_PIN_APPWIDGET', 'OPA_ENABLED', 'UPDATE_SMARTSPACE',
            'INSTALL_SHORTCUT.1', 'SESSION_COMMITTED', 'APPWIDGET_HOST_RESTORED', 'SET_WALLPAPER.1', 'PrimeActivity', 'CROP_AND_SET_WALLPAPER',
            'APPLY_ICON_THEME', 'SAMPLE_CODE', 'MORE_NEWS_ACTION', 'PRELOAD_WORKSPACE', 'UNINSTALL_SHORTCUT.1', 'ACTION_NOTIFICATION_TOOLBAR', 'ACTION_SIDEBAR',
            'droid', 'RETRY', 'executable', 'REMOTE_ACTION', 'APP_GALLERY', 'CROP', 'SELECTED_ALTERNATIVE', 'SEC_APPLICATION_SETTINGS', 'APP_SERVICE',
            'WakedReceiver', 'FetchOutlineMsgService', 'APPLY_THEME', 'THEME_CHANGED', 'COUNTER_CHANGED', 'BADGE_COUNT_UPDATE', 'SET_NOTIFICATION',
            'CHANGE_APPLICATION_NOTIFICATION_NUM', 'APPLICATION_MESSAGE_UPDATE', 'UPDATE_NOTIFICATION', 'toggleplayback', 'notificationvisibility',
            'IDP_LOGIN_REQUEST', 'ADD_ACCOUNT', 'SIGN_UP_ACCOUNT', 'PICK_ACCOUNT', 'PUSH_BACKUP', 'PUSH_BACKUP_IF_NEEDED', 'GET_TICKET', 'UPDATE_PROFILE',
            'SIGN_OUT', 'SIGN_OUT_ALL_APPS', 'SSO_SERVICE', 'mobiroller', 'IMAGE_CAPTURE', 'STILL_IMAGE_CAMERA', 'MainService', 'default',
            'INITIALIZE_PROGRAMS', 'PREVIEW_PROGRAM_ADDED_TO_WATCH_NEXT', 'DISABLE_CALLER', 'HelpActivity', 'USER_UNLOCKED', 'VIEW_LIST', 'camera.1', 'vpn',
            'IMAGE_CAPTURE_SECURE', 'STILL_IMAGE_CAMERA_SECURE', 'VIDEO_CAMERA', 'VIDEO_CAPTURE', 'PLATFORM_THREAD_20150314', 'DICT_DECAY', 'UPDATE_NOW',
            'NOTIFICATION_CLICK', 'NOTIFICATION_CANCEL', 'AlarmReceiver', 'SUGGESTION_PICKED', 'push', 'theme', 'APP_START', 'SECRET_CODE', 'player',
            'PP_LOGGER_ACTION', 'GET_VERSION', 'keyboard', 'news.1', 'profile', 'login', 'browserimp', 'web', 'DOWNLOAD_WAKEUP', 'DOWNLOAD_OPEN',
            'DOWNLOAD_LIST', 'DOWNLOAD_HIDE', 'dp', 'in', 'gin', 'oin', 'rno', 'SET_THEME', 'LAUNCHER_PREFERENCES', 'DOWNLOAD_UPDATE',
            'NOTIFICATION_DOWNLOAD_START', 'NOTIFICATION_DOWNLOAD_UPDATE', 'NOTIFICATION_DOWNLOAD_COMPLETE', 'NOTIFICATION_DOWNLOAD_STOPPED',
            'NOTIFICATION_DOWNLOADS_PAUSED', 'ACTION_PLAY_PAUSE', 'SpellCheckerService', 'geofence', 'REMINDER', 'test', 'MuzeiArtSource', 'DBXC_EDIT',
            'DBXC_VIEW', 'THEME', 'ACTION_UPDATE_WIDGET', 'ACTION_CLICK', 'ACTION_WIDGET_CONFIGURE', 'PLAY_VIDEO', 'restart', 'SENDTO',
            'ACTION_PASSWORD_FAILED', 'ACTION_PASSWORD_SUCCEEDED', 'reader', 'QS_TILE_PREFERENCES', 'THEME_APPLIED', 'UNKNOWN_CLIENT', 'DOWNLOAD', 'launcher',
            'al', 'lock', 'notifications', 'general', 'scan', 'Profile', 'About', 'partner', 'apps', 'guide', 'ACTION_BATTERY_OKAY', 'ACTION_DATE_CHANGED',
            'ACTION_SCREEN_ON', 'MEDIA_BAD_REMOVAL', 'intent', 'message', 'PLATFORM_THREAD_20150311', 'ACTION_REPLY', 'ACTION_DELETE', 'ACTION_DISMISS',
            'ACTION_CLEAR', 'ACTION_BROADCAST_INTERACTION', 'ACTION_BATTERY_CHANGED', 'delete', 'SCAN_MODE_CHANGED', 'RINGER_MODE_CHANGED', 'downloadapp', 'on',
            'ACTION_MAIN', 'ATTACH_DATA', 'ACCOUNT_CHANGED', 'MediaRouteProviderService', 'CONFIG', 'COMPANION_CONFIGURATION', 'REGISTER_AGENT',
            'ChooserTargetService', 'MANAGE_NETWORK_USAGE', 'SettingActivity', 'TokenSharingService', 'AppCallResultBroadcast', 'PUSH_SERVICE_START', 'lite',
            'wallpaper', 'show_check', 'activate.1', 'deactivate', 'CANCEL_KEYBOARD_INSTALL_NOTIFICATION', 'MEDIA_SHARED', 'action_notify', 'STATISTIC',
            'browser', 'PUSH_SERVICE', 'quotes', 'PACKAGE_FIRST_LAUNCH', 'ACTION_START_SERVICE', 'APP_EMAIL', 'FORWARD', 'REPLY_ALL', 'REPLY', 'CREATE_ACCOUNT',
            'ACCOUNT_MANAGER_ENTRY', 'install', 'ACTION_VIEW_DETAIL', 'VOLUME_STATE_CHANGED', 'ALL_APPS', 'shortcuts', 'custom', 'BROWSE', 'Detail',
            'QUICK_VIEW', 'ACTION_CANCEL', 'GO_TO_MARKET', 'status', 'CONFIGURATION_CHANGED', 'SENSOR_ALARM', 'REMINDER_EXPIRED', 'wake', 'PUSH_RECEIVED',
            'arabic', 'xiaoying', 'JNotifyActivity', 'FILEPICKER', 'EDITORFILEPICKER', 'CAMERA.1', 'demo', 'ACTION_SDK_RESP_ACTIVITY', 'UNREGISTRATION',
            'completed', 'opened', 'USER', 'MISC', 'CONTENTS', 'INTERACTION', 'TASK', 'finish', 'progress', 'ScanProject', 'ALARM_DISMISSED', 'ALARM_CLEARED',
            'com_ufotosoft_action_image_fixed_crop', 'com_ufotosoft_action_guideline_fixed_crop', 'com_ufotosoft_action_guideline_fixed_crop_blur', 'Setting',
            'CALL_BUTTON', 'TOUCH_DIALER', 'RECENT_CALLS', 'TAB', 'SHOW_MISSED_CALLS_NOTIFICATION', 'dog', 'PushNotification', '6184556697063849985a', 'FRIEND',
            'unlock', 'SETTING', 'DICTIONARY_SEARCH', 'OPEN_DICTIONARY', 'ENUMERATE_DICTS', 'query', 'SPINNER_DATACHANGED', 'ACTION_WIDGET_REFRESH',
            'ACTION_WIDGET_SETTING', 'ACTION_WIDGET_SECTION_UPDATE', 'ACTION_LANGUAGE_UPDATE', 'SAVE_ARTICLE', 'BUBBLESTYLE', 'CLOCKFONTS', 'APP_CALENDAR',
            'INIT', 'WAKE_UP', 'DownloadService', 'staff', 'LICENSE', 'NOTIFICATION_DELETE', 'SupportActivity', 'SETUP_WIZARD', 'MAIN_ACTIVITY', 'LAUNCH_APP',
            'BIND_SERVICE', 'PROVISIONING_SUCCESSFUL', 'INSTALL_PACKAGE', 'PROFILE_PROVISIONING_COMPLETE', 'DEVICE_ADMIN_SERVICE', 'splash', 'dialog', 'logout',
            'PRELOAD', 'Default', 'start_service', 'photoeditor', 'DisableNotifications', 'main_process_action', 'THEMES', 'ACTION_PICK_ICON', 'themes',
            'apk_action', '1', 'TWO', 'ACTION_ICON', 'CUSTOM_ICON_PICKER', 'THEME_ICONPACK', 'THEME_SCENE', 'THIRD_PART_EDIT', 'THIRD_PART_CONVERT_RESULT',
            'UmengReportReceiver', 'FileDownloaderService', 'PlayService', 'FxService', 'DISPLAY', 'RINGTONE_PICKER', 'AUTH', 'SCORE',
            'HANDLE_AUTHORIZATION_RESPONSE', 'MUSIC_PLAYER', 'AUDIO_PLAYER', 'APP_MUSIC', 'previous', 'show', 'STOP_SERVICE', 'started', 'failed',
            'BUBBLEICONS', 'CLOCKS', 'ONDESTROY', 'MEDIA_SEARCH', 'UPDATE_ACTION', 'DEBUG', 'applications', 'NOTIFICATION_CANCELED', 'v1',
            'PREVIEW_PROGRAM_BROWSABLE_DISABLED', 'CONTACT_US', 'TOGGLE_PLAYBACK', 'URL', 'connection', 'up', 'it', 'SCHEDULE_MEMORY_USAGE_CHECKING',
            'EXECUTE_MEMORY_USAGE_CHECKING', 'BOOST_APP_MEMORY_USAGE_NOTIFICATION_CLICKED', 'BOOST_NOTIFICATION_DELETE', 'CPU_COOL_DOWN_CLICKED',
            'CPU_NOTIFICATION_DELETE', 'CLEAN_CLICKED', 'CLEAN_NOTIFICATION_DELETE', 'NOTIFICATION_CLICKED', 'JUNK_NOTIFICATION_CLICKED',
            'HIDE_NOTIFICATION_CLICKED', 'JUNK_NOTIFICATION_DELETE', 'HIDE_NOTIFICATION_DELETE', 'JUNK_NOTIFICATION_CLEAN', 'DOWNLOAD_SERVICE',
            'SEARCH_LONG_PRESS', 'plugin', 'RWUpdateAppReceiver', 'ConnectionService', 'VOICE_LAUNCH', 'Start', 'Stop', 'RestartSensor',
            'ACTION_PURCHASE_SCREEN', 'SHOW_OVERLAY', 'ADD_JOB_CREATOR', 'SHEPHERD2_CONNECTIVITY_FAILSAFE', 'UPDATE_ATTEMPT_FINISHED', 'IDS_REQUEST',
            'REFRESH_LIST', 'ANY_DATA_STATE', 'CLOSE_SYSTEM_DIALOGS', 'applock', 'ROOTSERVICE', 'SOCIAL_SHARE', 'PURCHASE', 'PURCHASE_FROM_REMOVE_ADS_CARD',
            'ACTION_MAIN_SCREEN', 'NATIVE_AD_CACHE_ACTION', 'CHANGE', 'SHARE', 'MAINACTIVITY', '0', '3', '4', '5', '6', 'UPDATE_SHORTCUT.1', 'UPDATE_BADGE.1',
            'SCORES_UPDATE', 'LOADING', 'BROWSER', 'jump', 'WIFI_SETTINGS', 'BOOKMARK_APPWIDGET_UPDATE', 'START_TEXT_QUERY', 'START_VOICE_QUERY',
            'UPDATE_ALL_WIDGETS', 'CLICK_NOTIFICATION', 'CLOSE_NOTIFICATION', 'DOCUMENT_PIN_STATE_CHANGED', 'ACTION_NEW_MESSAGE', 'ACTION_FAILED_SEND',
            'ACTION_NEW_FRIEND_INSTALL', 'ACTION_READ_THREAD', 'ACTION_NEW_BUILD', 'ACTION_LOGGED_OUT_MESSAGE', 'ACTION_CLEAR_THREAD',
            'ACTION_CLEAR_FRIEND_INSTALL', 'ACTION_CLEAR_NEW_BUILD_NOTIFICATION', 'ACTION_CLEAR_ALL_NOTIFICATIONS', 'RETRY_UPLOAD', 'GET_PHONE_ID', 'SHARE_IDS',
            'ACTION_WAKEUP', 'resume', 'SHARED_QE_FLAG_REQUEST', 'ready', 'clear_message', 'ACTION_FBNS_STARTED', 'ACTION_FBNS_STOPPED',
            'IS_MANAGED_APP_CHANGED', 'notification_cancelled', 'notification_clicked', 'ALARM_ACTION', 'TOS_ACKED.1', 'favorite', 'playpause', 'playmode',
            'shuffle', 'update_all', 'update_progress', 'update_playmode', 'update_favorite', 'update_skin', 'GTALK_CONNECTED', 'SCAN_RESULTS', 'RSSI_CHANGED',
            'DOWNLOAD_CANCEL', 'DELETE_NOTIFICATION', 'CALL_NOTIFICATION', 'katana', 'go', 'IOpenVPNAPIService', 'prediction', 'START_SYNC', 'CONFIG_DIGITAL',
            'INPUT_METHOD_CHANGED', 'MY_OWN_WIDGET_UPDATE', 'WEB_CLIENT', 'ACTION_HEADSET_PLUG.1', 'METHOD', 'BIND_SYNC', 'gps.1', 'ID_BROADCAST', 'Page',
            'AUTO_DOWNLOAD', 'ADS_UPDATE', 'shortcut', 'free', 'APP', 'PICK_FILE', 'PICK_DIRECTORY', 'PlayPause', 'UPDATE_SETTINGS', 'LOCATION_UPDATE',
            'GEOFENCE', 'androidapp', 'magzter', 'IDownloadService', 'reader_sp', 'SMS_SENT', 'AlarmTriggeredEvent', 'unitedkiosk', 'ACTION_PURCHASE', 'dims',
            'UPLOAD_SUCCESS', 'UPLOAD_FAILURE', 'app2', 'quickcover', 'unconditional', 'jumpforward', 'toggle', 'KEEP_ALIVE', 'GIMBAL_SERVICE',
            'ACTION_STOP_RADIOPLAYER', 'ACTION_STOP_MEDIAPLAYER', 'INTENT_PLAYPAUSE', 'INTENT_OPENPLAYER', 'INTENT_CANCEL', 'refreshls', 'RUN', 'WIDGET_UPDATE',
            'DATA_UPDATED', 'launch', 'en', 'ui', 'LOCATION_UPDATES', 'REFRESH_DONE', 'CUSTOM_INTENT', 'OPEN_SETTINGS', 'ACTION_MY_PACKAGE_REPLACED',
            'PackageStateReceiver', 'SmsHandlingService', 'IpcMessageService', 'IpcNotificationService', 'NotificationService', 'english',
            'BACKGROUND_DATA_SETTING_CHANGED', 'SYNC_CONN_STATUS_CHANGED', 'set', 'requestAccounts', 'SET_ALARM.1', 'premierleague', 'SocialPlugin',
            'FORCE_WIDGET_UPDATE', 'STOP_WIDGET_UPDATE', 'NOTIFY_BUTTON_RECEIVER', 'THEME_APPLY', 'EXTERNAL_APPLICATIONS_UNAVAILABLE', 'DialogShowPicker',
            'TIME_CHANGED', 'INTENT_ACTION', 'stopBugging', 'ABOUT', 'lifeinsurancetrandingforexonline', 'layout', 'images', 'EDIT_NOTE', 'reporter',
            'translator', 'CHOSEN_COMPONENT', 'www', 'NEXT_BUTTON_CLICK', 'OPEN_WORD', 'ENCODE', 'ScreenStateService', 'notification_click',
            'CATEGORY_PREFERENCE', 'com', 'OPEN_URL', 'FIRSTRUN', 'NOTIFICATION_ACTION_TAPPED', 'STARTED', 'promobile', 'TIMEOUT', 'ACTION_REMINDER',
            'NEW_NOTIFICATION', 'CRASH', 'SIGNIN', 'API', 'LIBRARY_SERVICE', 'NotificationCleared', 'PlaybackService', 'ALERT', 'CDS_DOWNLOAD_START',
            'CDS_RESTORE_USER_ITEMS', 'Alarm', 'BB10_BOOT_COMPLETED', 'ACTION_EXTERNAL_APPLICATIONS_AVAILABLE', 'ENTERED_GEOFENCE', 'EXITED_GEOFENCE',
            'SERVICO_TEST', 'HELLO', 'lockscreen', 'AboutActivity', 'AUDIO_STATE_CHANGED', 'wattpad', 'wpbeta', 'remove', 'CLICK_ACTION_EVENT', 'GET_AD_ID',
            'reminder', 'generator', 'TWEET_COMPOSE_CANCEL', '8BITCLOCK_WIDGET_UPDATE', 'editor', 'ACTION_USER_PREFERENCE', 'ProxyBootService',
            'START_REFERRER', 'SEARCH_BOOK_CONTENTS', 'DID_RANGING', 'DID_MONITORING', 'gcmdemo', 'm', 'SEND_LOG', 'HANDLE_EVENT', 'SPLASH', 'ICON_PACK',
            'ACCOUNT', 'gratis', 'production', 'admin', 'MediaPlayerService_ACTION', 'ACTION_BATTERY_LOW', 'PrintService', 'OPEN_TRACKING', 'bg',
            'ACTION_ALARM', 'goodnewsofjesus', 'AudioAction', 'payment', 'merchant', 'ACTION_PREVIOUS', 'ACTION_NEXT', 'gcmexample', 'FAVOURITE_SAVE',
            'FAVOURITE_REMOVE', 'SentNotification', 'OpenedNotification', 'sdk', 'MANAGED_PROFILE_PROVISIONED', 'LICENSE_STATUS', 'result', 'failure',
            'APPLICATION_FOCUS_CHANGE', 'EMAIL_ACCOUNT_ADD_RESULT', 'EMAIL_ACCOUNT_DELETE_RESULT', 'UPDATE_FOTA_VERSION_RESULT', 'EXCHANGE_CBA_INSTALL_STATUS',
            'CBA_INSTALL_STATUS', 'EXCHANGE_ACCOUNT_ADD_RESULT', 'EXCHANGE_ACCOUNT_DELETE_RESULT', 'behavior', 'SIM_CARD_CHANGED', 'CALL_STATE',
            'APPLICATION_RESTRICTIONS_PROXY', 'READ.1', 'UPDATE_STATUS', 'restartService', 'SHOW', 'pro', 'ANNOUNCEMENT', 'flashlight', 'CHOOSER',
            'REGISTER_MODE', 'CREATE_FILE', 'EDIT_FILE', 'VIEW_FILE', 'CALL_PRIVILEGED.1', 'quran', 'events', 'ACTION_RICHPUSH_CALLBACK', 'CALL', 'PLUGIN.1',
            'fr', 'snappy', 'BackgroundAction', 'dtw', 'application', 'GSM_SMS_RECEIVED', 'DATA_SMS_RECEIVED', 'disable', 'Login', 'TOGGLEPLAYBACK', 'PREVIOUS',
            'PAIRING_CANCEL', 'CHAT', 'pushnotification', 'ACTION_CLOSE', 'START_ALARM_ACTION', 'OFFLINE_SUBMIT', 'FIRE', 'CANCEL_DOWNLOAD', 'START_DOWNLOAD',
            'Library', 'CREATE_NOTE', 'PURCHASES_UPDATED', 'activities.1', 'CAPABILITY_CHANGED', 'business', 'NORMAL', 'PRESENT_ACTION', 'hub',
            'OPEN_MAIN_ACTIVITY', 'appsgeyser', 'REMOTE_SERVICE', 'broadcast', 'EVENT', 'StartServiceReceiver', 'stack', 'ACTION_PRINT',
            'CONNECTION_STATE_CHANGE', 'victorybaptistsc', 'DELAYED_NOTIFICATION', 'CAMERA_BUTTON', 'UMS_DISCONNECTED', 'DEVICE_IDLE_MODE_CHANGED',
            'ACTION_PASSWORD_CHANGED', 'eventapp', 'plus', 'HOOKEVENT', 'quiz', 'ACTION_DEVICE_ADMIN_DISABLE_REQUESTED', 'RESTART_APP',
            'OPEN_NOTIFICATION_ACTIVITY', 'LOCATION_CHANGED', 'jobs', 'GCM_RECEIVED_ACTION', 'ACTION_GEOFENCE_TRANSITION', '8ec17871', 'MainDashboard',
            'dismiss', 'view', 'INSERT_OR_EDIT', 'DIALER', 'MESSAGES', 'ACTION_FORWARD', 'SEND_MESSAGE_TO_CONTACTS', 'VOICE_SEARCH_RESULTS', 'CANCEL_PUSH',
            'malimalihome', 'SEARCHLIB_APPLICATION_INSTALLED', 'SEARCHLIB_APPLICATION_UPDATED', 'NOTIFICATION_START', 'CLIDABLE', 'BAR_MARKER_SERVICE',
            'PACKAGE_VERIFIED', 'FINISH', 'ACL_DISCONNECT_REQUESTED', 'global', 'request', 'BCPOST', 'LIBRARY_PICKER', 'DISCONNECT', 'WAKEUP',
            'NOTIFICATION_SERVICE', 'OPEN_ACTIVITY', 'SKIN', 'metachanged', 'playstatechanged', 'playbackcomplete', 'queuechanged', 'metadatachanged',
            'DISPLAY_AUDIO_EFFECT_CONTROL_PANEL', 'OPEN_AUDIO_EFFECT_CONTROL_SESSION', 'CLOSE_AUDIO_EFFECT_CONTROL_SESSION', 'AUTO_UPDATE', 'SMS_DELIVER',
            'google', 'SHOW_NOTIFICATION', 'TRACK', 'ACTION_APP_TO_FOREGROUND', 'LOGOUT', 'PICKER', 'CLEAR', 'TaskService', 'HTC_RINGTONE_PICKER', 'ru',
            'CDS_RESTORE_OWNED_PACKS', 'CDS_DOWNLOAD_EXTRA_ASSETS', 'HANDLE_CALL', 'SipConfiguration', 'AIRSHIP_READY', 'RestartService', 'WELCOME',
            'BUG_REPORT', 'PINNED_DOCUMENT_CONTENT_STATUS_CHANGED', 'ACTION_FORCE_RESUME_SYNC', 'VIEW_DOWNLOADS', 'ACTION_TIME_TICK', 'ACTION_TIMEZONE_CHANGED',
            'cycle', 'later', 'googlefit', 'SYNC_ACTION', '16', 'NotificationReceiver', 'retry', 'TvInputService', 'action_nextgen_edit', 'everpro',
            '6184556654793654273a', 'DICTIONARY', 'others', 'CROSS_PROMO', 'endofplayback', 'playbackstatechanged', 'MUSIC_STATUS', 'ACTION_PLAYBACK_PLAY',
            'ACTION_PLAYBACK_PAUSE', 'TRACK_COMPLETED', 'ACTION_SKIPPED', 'ACTION_PAUSED', 'ACTION_TRACK_STARTED', 'ACTION_NOTIFICATION_DISMISS',
            'ACTION_DOWNLOAD_COMPLETE_DELAYED', 'CDS_VERIFY_SUBSCRIPTIONS', 'QUERY_CONDITION', 'TEST', 'Editor', 'ShareActivity', 'GLOBAL_SEARCH',
            'CustomTabsService', 'BEACON', 'TRIGGER', 'AUTO_SEND', 'SELF_NOTE', 'SWITCHUSER', 'FTPSERVER_STARTED', 'FTPSERVER_STOPPED',
            'ACTION_START_FTPSERVER', 'ACTION_STOP_FTPSERVER', 'REFRESH_PUSH_CHANNEL', 'PUSH_ON', 'YouWillNeverKillMe', 'ACTION_SCHEDULED_JOB', 'TASK_REMOVED',
            'LeanplumPushListenerService', 'buyerapp', 'WIDGET_REFRESH', 'background', 'NEW_MESSAGE', 'tv', 'CREATE', 'unsettledevent', 'LWPInfo',
            'TYPE_HYPERPUSH_CUSTOM', 'OPUSSERVICE', 'MSGRECVD', 'SHARED_THEME_ACTIVATED', 'SHARED_THEME_UPDATED', 'RESET', 'net', 'ACTION_BROADCAST_ALARM_JOB',
            'ACTION_BROADCAST_CLICK_REMINDER', 'ACTION_BROADCAST_CLICK_GOAL', 'ACTION_BROADCAST_CLICK_NEW_RECORD', 'ACTION_TOGGLE', 'FeedbackActivity',
            'ACTION_APP_FIRST_LAUNCH', 'shop', 'READING', 'OPEN_NOTIFICATION', 'WIFI_AP_STATE_CHANGED', 'UPDATE_ALARM', 'ACTION_LOGIN_RESULT',
            'ACTION_SYSTEM_ADD_ACCOUNT', 'YA_SDK_LOGIN', 'BIND_SOCIAL_APPLICATION', 'BIND_SOCIAL_ACCOUNT', 'NATIVE_SOCIAL_VKONTAKTE_AUTH',
            'NATIVE_SOCIAL_GOOGLE_AUTH', 'NATIVE_MAILISH_GOOGLE_AUTH', 'SEND_AUTH_TO_TRACK', 'NATIVE_SOCIAL_FACEBOOK_AUTH', 'ACTION_SSO_ANNOUNCEMENT',
            'later_show', 'exercisesnooze', 'kids', 'PAYMENT', 'card', 'servicebinded', 'statechanged', 'GEOFENCE_ALARM', 'REVIEW_NOTIFICATION_ALARM',
            'GEOFENCE_REGISTER', 'ACTION_QUICK_CHECKIN', 'starter', 'informa', 'child', 'STATUS', 'AutofillService', 'VIEW_DIRECTORY', 'BROADCAST_STATUS',
            'restartservice', 'PRINT', 'teacher', 'OPEN_APP', 'DISMISS_NOTIFICATION', 'exercisesnooze_later', 'openurl', 'LoginActivity',
            'NOTIFICATION_SELECTED', 'NOTIFICATION_DELAYED', 'effect', 'scheduleIntent', 'wakeLockRelease', 'mail.1', 'POLICY_INTENT', 'ACCOUNT_INTENT',
            'RESEND_NOTIFICATIONS', 'CLEAR_NEW_MAIL_NOTIFICATIONS', 'update_notification', 'MARK_READ', 'EXCHANGE_INTENT', 'ACTION_SCREEN_OFF', 'UNREGISTER',
            'ACTION_NOTIFICATION', 'WEBVIEW', 'VOICE', 'PAY', 'PROFILE_MEDIA_CREATE', 'twemoji', 'emojione', 'es_us', 'sticker', 'LocalAppDetailActivity',
            'LocalFragmentActivity', 'msgcontentactivity', 'msgnotifyactivity', 'Effect', 'LanguageSetting', 'EmojiStyle', 'InAppBillingActivity',
            'ApplyActivity', 'InAppBillingActivityForTheme', 'ApplyActivityForMain', 'ApplyActivityForTheme', 'NotificationGuideToStoreReceiver',
            'ThemeNotificationReceiver', 'ThemeConmunicationService', 'services.1', 'SEND_RATING_REQ', 'CDOID', 'WHITELABEL_ID', 'INITSDK', 'COMM_END',
            'WIC_POSITION', 'MAKE_CALL', 'TRIGGER_SEND', 'PACEMAKER', 'DYNAMIC_RE_ENGAGEMENT', 'PRIORITY', 'HEARTBEAT', 'SET_CUSTOM_ICON', 'CONTACT_MANUAL',
            'TARGETING', 'SPAM_REQUEST', 'SCRAPPING_COMM_END', 'THROTTLE', 'DATA_CLEARED', 'LoginShim', 'fathom', 'Authenticate', 'ProAuthenticate',
            'BrandUser', 'ContactForm', 'SaveProperty', 'EditSaveProperty', 'SaveSearch', 'EditSaveSearch', 'AddressValidateAndSearch', 'CombinedResultScreen',
            'SearchResultsList', 'SearchResultsGallery', 'SearchResultsMap', 'OfficeAgentSearch', 'OfficeAgentSearchResult', 'ListingNumberSearch',
            'PopupRefineActivity', 'SavedSearchList', 'AdvancedUIPropertyList', 'ResultDetail', 'PhotoShow', 'AdvancedSearch', 'ggarsc', '7', '8', '9', '10',
            'GAME', 'Launch', 'APPWIDGET_SCHEDULED_UPDATE', 'ACTION_STUB_PLUGIN', 'PLUGIN_DEFAULT', 'NOTIFICATION_DISMISS', 'UPDATE_WIDGET_ACTION',
            'START_UPDATING_WIDGET_ACTION', 'COMPLETE_UPDATING_WIDGET_ACTION', 'LOCATION_READY', 'ACTION_APPWIDGET_CHANGE_LOCATION',
            'ACTION_APPWIDGET_CHANGE_SETTINGS', 'ACTION_APPWIDGET_START_ACTIVITY', 'PAYMENT_STATUS_CHANGED',
            'AUTO_SYNC', 'STOP_TRACKING', 'monitor', 'PERMISSION_RESULT_INTENT', 'ACTION_DOCK_EVENT', 'drawing', 'gallery', 'edit', 'PRINT_SETTING',
            'REQUEST_UPDATE_INFORMERS', 'UPDATE_BATTERY', 'UPDATE_STANDBY_BUCKET', 'INFORMERS_UPDATE_STARTED', 'INFORMERS_UPDATED',
            'INFORMERS_UPDATE_CANCELLED', 'MINI_DISK', 'CANCEL_ACTION', 'STOP_ACTION', 'CommonWebViewNew', 'page', 'COMPLETE', 'ACTION_PUSH_CHANGE', 'PUSH_MSG',
            'record', 'RESPONSE', 'REGISTRY', 'SHARE_SERVICE', 'baseline', 'filedownload', 'INSTALL', 'TRUSTED_WEB_ACTIVITY_SERVICE', 'ADDBOOKMARK',
            'ACTION_START_WEBAPP', 'ACTION_START_WEBAPK', 'browser_action_open', 'AUTH_TOKEN_REQUEST', 'VoiceInteractionService', 'music', 'matches',
            'COMPUTER_LAUNCHER_THEME', 'v2', 'playlist', 'talk.1', 'APPWIDGET_DISABLE', 'TWITTER_LOGIN', 'TASKS_UPDATED', 'ACTION_DEVICE_ADMIN_DISABLED',
            'WebViewActivity', 'Search', 'UNINSTALL_PACKAGE', 'WAP_PUSH_DELIVER', 'upgrade', 'RESPOND_VIA_MESSAGE', 'calculator', 'gray', 'SCANNER',
            'LAUNCH_WEBVIEW', 'EMERGENCY', 'ACTION_WIDGET_MUSIC', 'MusicPlayService', 'ADVANCED_SETTINGS', 'SETTINGS_CHANGED', 'ACTION_EDIT_EVENT',
            'MY_CUSTOM_ACTION', 'sec_btn', 'dev', 'SUBSCRIBE_SERVICE', 'action_receiver_deep_link_handle', 'action_receiver_in_nox',
            'action_receiver_gp_in_nox', 'action_receiver_official_in_nox', 'action_receiver_remove_notification', 'rewind', 'external', 'newtheme',
            'CHANGE_FONT_cNnogFgEw559ScbmyaoY', 'EMOJI_FONT_SETTING', 'STICKER2_ADD', 'MAUI_OPEN', 'PACK_THEME_DOWNLOAD', 'wallpapers', 'INIT_AND_UPDATE_NOW',
            'act_widget_nop', 'act_widget_open_app', 'act_widget_open_payment', 'act_widget_update_balance', 'act_widget_update_period',
            'act_widget_update_expiring', 'act_widget_next_page', 'act_widget_after_update_balance', 'act_widget_after_update_period',
            'act_widget_after_update_expiring', 'act_widget_open_link_must_update', 'SEARCH_SETTINGS', 'UPDATE_COVER', 'UPDATE_POSITION', 'PUSHIOPUSH', 'ro',
            'UID_REMOVED', 'CarrierService', 'MESSAGE_EVENT', 'ACTION_FEEDBACK', 'EDIT_NEW_MAIL', 'DEEPLINK', 'KEYBOARD', 'messages', 'AllCastSource',
            'TOP_UP_COUNTRY_LIST', 'TOP_UP_OPERATOR_LIST', 'TOP_UP_AMOUNT', 'TOP_UP', 'TOP_UP_CHECK_STATUS', 'itelmobiledialer', 'LOGGED_IN',
            'ACTION_GOSTATICSDK', 'RATE_LIMIT_SURPASSED', 'conversation', 'popup', 'gowidget', '3dwidget', 'CONTENT_CHANGED', 'MESSAGE_SENT',
            'IM_SMS_SENT_ACTION', 'SEND_MESSAGE', 'MESSAGE_STATUS_RECEIVED', 'SIM_FULL', 'SMS_REJECTED', 'timer', 'ACTION_TEST', 'GET_UNIQUE_ID',
            'HeroPlayerService', 'notes', 'Callback', 'ExpandableListActivity', 'terms', 'RECORD_SOUND', 'MY_PACKAGE_SUSPENDED', 'MY_PACKAGE_UNSUSPENDED',
            'CONFIGURE', 'CONFIGURED_NETWORKS_CHANGE', 'GET_RESTRICTION_ENTRIES', 'ACTION_DATA_UPDATED', 'Response', 'ACTOR_SELECTED',
            'SYSTEM_NOTIFICATION_DISMISSED', 'SYNC_REGISTRATION_STATUS', 'ANDROID_ACCOUNT_CHANGED', 'voice_recognition', 'jcloud', 'opaliNotifikaciju',
            'ACTION_SERVICE_VIDEO_DOWNLOAD_REQUEST', 'ACTION_SERVICE_VIDEO_DOWNLOAD_CANCEL', 'ACTION_SERVICE_VIDEO_DOWNLOAD_PAUSE',
            'ACTION_SERVICE_VIDEO_DOWNLOAD_RETRY', 'ACTION_SERVICE_VIDEO_DOWNLOAD_DELETE', 'ACTION_SERVICE_VIDEO_DOWNLOAD_RESTORE',
            'ACTION_SERVICE_VIDEO_DOWNLOAD_LATER', 'cbmls', 'app1', 'normal', 'wallet', 'about', 'add', 'CallScreeningService', 'AUTHORIZE',
            'ACTION_MESSAGE_HEARD', 'ACTION_MESSAGE_REPLY', 'TIMER', 'reactapp', 'active', 'vision', 'GSERVICES_CHANGED', 'draw_info_updated',
            'draw_info_manual_updated', 'customer', 'MMS_SENT', 'SMS_DELIVERED', 'mobileapp', 'consumer', 'channel', 'local.1', 'account', 'GET_APP_TOKEN_RSP',
            'fashion', 'QUICK_CONTACT', 'START_TRACKING', 'ev', 'CALLLOG', 'INCALL', 'SipService', 'Notification', 'im', 'HELP', 'ANSWER', 'members',
            'CHECK_UPDATE_RESULT', 'simple', 'needsRefresh', 'networkChanged', 'EVENT_DIRECTORY_CONTROLLER', 'MY_ACCOUNT_CONTROLLER',
            'EDIT_CUSTOM_SCHEDULE_ITEM_ACTIVITY', 'EXTERNAL_APPOINTMENT_ACTIVITY', 'EVENT_GUIDE_CONTROLLER', 'fire', 'ScreenshotReceiver',
            'LockedContentService', 'BroadcastNotificationPublisher', 'maker', 'vetrax2', 'ACCOUNT_ADDED', 'PIVOT', 'fitness', 'words', 'recieve',
            'CATCH_BEACON', 'trigger', 'DEL_GROUPED_MSG', 'NOTIFICATION_OPEN', 'MyReceiver', 'schedule', 'CANCEL', 'CLEAR_NOTIFICATION', 'INTENT_NEXT',
            'ACTION_NOTIFY_DATASET_CHANGED', 'REGISTER_BR', 'PRIORITY_ACTION', 'Message', 'MENU', 'EDIT_PROFILE', 'ACTION_MEDIA_MOUNTED', 'STYLE_GUIDE',
            'ACTION_OPEN_APP', 'UBER_MESSAGE', 'PUSH_NOTIFICATION_ACTION_CLICK', 'PUSH_NOTIFICATION_ACTION_DELETE', 'src', 'ACTION_PROCESS_UPDATE', 'horoscope',
            'beaconInitKey', 'NotificationActivity', 'SOCKET_EVENT_RECEIVED', 'sms', 'GET_ACCOUNTS.1', 'LOCATION.1', 'techtrainner',
            'ACTION_MANAGE_TRUSTED_WEB_ACTIVITY_DATA', 'MOTIONCHANGE', 'ACTIVITYCHANGE', 'PROVIDERCHANGE', 'POWERSAVECHANGE', 'HTTP', 'SCHEDULE', 'BOOT',
            'gchss', 'parent', 'DKEZAN_WIDGET_UPDATE', 'dejaloYa', 'rwadams', 'live', 'courses', 'UpdateService', 'calendar', 'game', 'wgbcv', 'tgcustom',
            'Splash', 'beta', 'ACTION_ALERT_CALLBACK', 'reportCrash', 'huisgenoot', 'SERVICE_ACTION_INITIALIZE', 'POLL', 'ACTION_LOCKED_BOOT_COMPLETED',
            'CONNECT', 'CONNECTION_TIMEOUT', 'my', 'ApplicationSetUp', 'newcar8891', 'AVIARY_CONTENT_MANAGER', 'APP_MESSAGING', 'APP_CALCULATOR', 'myaccount',
            'lingodeer', 'MYCLASSFACULTYSTUDENTS', 'DOWNLOADS', 'MAPACTIVITY', 'network294', 'fma', 'INCOMING_CALL', 'SAVE_CACHE', 'LOAD_CACHE', 'SET_ITEM',
            'DOWNLOADED', 'primary', 'IVpnStateService', 'release', 'MetricsService', 'SEND_REGISTRATION', 'MESSAGE_OPENED', 'IOT_LAUNCHER', 'athlete',
            'TRIGGER_EVENT', 'NOTIFICATION_EVENT', 'ACTIVATE', 'TrustedWebActivities', 'plusgps', 'SNOOZE_ALARM', 'chat', 'ACTION_PUSH',
            'ACTION_DOWNLOAD_COMPLETE', 'PROCESS_STARTED', 'prod', 'LOGINACTIVITY', 'START_ALARM', 'DRIVE_OPEN', 'core', 'portfolio', 'truecloud',
            'dailydevotionapp', 'custom_firebase_event', 'recovered', 'impression', 'provider.1', 'onboardPatient', 'doSync', 'inviteFromPatient',
            'physicianToPhysicianReferralInvite', 'barebones', 'ACTION_DEFAULT', 'CaptureActivity', 'GenericWebViewActivity', 'REQUEST', 'SettingsActivity',
            'PLAYBACK_VIEWER', 'SCAN_DEVICES', 'PUSH_NOTIFICATION', '_BOOT_COMPLETED', 'NOTIFICATION_BUTTON', 'go_detail', 'go_detail_noti',
            'INTERNAL_SERVER_ERROR', 'NETWORK_ERROR', 'ACTION_PLAY_NOTIFICATION', 'CLEARNOTI', 'REG_CONNECTIVITY', 'START_DOWNLOAD_SERVICE',
            'START_NOTIFY_SERVICE', 'ACTION_OPEN_ALBUM', 'ACTION_LOUNGE_PLAY_SONG', 'ACTION_PLAY_SONGINFONOTI', 'CLOSENOTI', 'ACTION_UPGRADE', 'AGENT_CREATED',
            'DATA_PUSH', 'APPID_GOT', 'ICapptainService', 'online', 'school', 'POWER_CONNECTED', 'ChargeBatteryActivity', 'GETDEVICEUUID', 'SIGN_IN',
            'DREAMING_STOPPED', 'NEWID', 'CONFIGURATION', 'mainClick', 'INITIALIZATION_TIMEOUT', 'PUSH_SERVICE_STOPPED', 'INTERNET_OFF', 'INTERNET_ON',
            'bestpicture', 'SwrveUnityWakeful', 'MARU_SCORE_CENTER_SYNC', 'MARU_SCORE_CENTER_WELCOME', 'CONTENT', 'TOGGLE_BACKGROUND_AUDIO',
            'PLAY_BACKGROUND_AUDIO', 'PAUSE_BACKGROUND_AUDIO', 'STOP_BACKGROUND_AUDIO', 'UPDATE_BACKGROUND_AUDIO_NOTIFICATION', 'Mobile', 'unity', 'forward',
            'preview', 'drink', 'PLAY_RADIO', 'OPEN_ACTIVITY_2', 'AUTHENTICATE', 'FEED_SUPER', 'View', 'ForceUpgrade', 'droidx_library', 'openbook',
            'ACTION_PREV', 'navigation', 'map', 'delivery', 'ACTION_ON_ALARM', 'CronReceiver', 'radio', 'sergio', 'BackgroundService', 'paytm',
            'widgetTele7Click', 'pedometer', 'mobilebanking', 'SERVICE_START', 'CLOSEAPP', 'prefetch', 'kristineelezaj', 'PRE_BOOT_COMPLETED',
            'PACKAGE_NEEDS_VERIFICATION', 'banking', 'MAPKIT_ELECTION_ACTION', 'MAPKIT_VERSION_ACTION', 'MAPKIT_VICTORY_ACTION', 'northshorerealty', 'a2a',
            'INTENT_PLAYER', 'dating', 'olsonagency', 'passenger', 'ACTION_LOGIN', 'taximachine', 'sms_entregue', 'sms_enviado', 'drivermachine',
            'absolutecharm', 'rc', 'OPEN_MAIN_1', 'package_added', 'taxi', 'tr', 'PUSH_START', 'rider', 'TOKEN_CHANGED', 'ExternalReceiver', 'pruutah',
            'Settings', 'pmh', 'HOS_DIAGNOSTIC_LIST_DIALOG', 'ACTION_PLAYER_STOP', 'ACTION_PLAYER_PLAY', 'SAVE', 'everydaystart', 'famcal',
            'AndroidMobilePushApp', 'alarm_killed', 'cancel_snooze', 'sleep_timer', 'WIDGET_CONFIGURED', 'TOGGLE', 'remind', 'dc', 'activation', 'Analysis',
            'parentsapp', 'PLAY_ONDEMAND', 'PAUSE_ONDEMAND', 'PLAY_PAUSE', 'STOP_ONDEMAND', 'PLAY_PAUSE_ONDEMAND', 'CHANGE_CLID', 'smartapps', 'smartcross',
            'action_reg_msg', 'action_check_saved_message', 'NOTIFICATION_LAUNCH_ACTIVITY', 'ACTION_LOCKER_ACCOUNT_CHANGE', 'vip', 'RemindersActivity',
            'string', 'CATEGORY_APP_MUSIC', 'ACTION_WIDGET_PLAY', 'ACTION_WIDGET_BACK', 'ACTION_WIDGET_NEXT', 'ACTION_WIDGET_OPEN', 'ACTION_WIDGET_SHUFFLE',
            'ACTION_WIDGET_REPEATE', 'ACTION_POWER_PROBE', 'CATEGORY_CONTENT_MUSIC', 'qustodioapp', 'charlottesmith', 'millcreekchurch', 'CLICK_ACTION',
            'ACTION_PROCESS_DIRECTIVE', 'CATEGORY_CAPABILITY_AGENT', 'report', 'new_message', 'CLOCK_UPDATE', 'NEWS', 'NewsMemoryNotification',
            'ACTION_CLEAR_PUSHES', 'umeng', 'COCKROACH', 'PROGRAM_ALARM', 'HISTORY', 'restore', 'mb32b', 'POWER_DISCONNECTED', 'EMS_PUSH_RECEIVED',
            'EMS_SHOW_NOTIFICATION', 'EMS_OPEN_NOTIFICATION', 'ACTION_NOTIFICATION_BUTTON_PAUSE', 'ACTION_NOTIFICATION_BUTTON_NEXT',
            'ACTION_NOTIFICATION_BUTTON_PREV', 'ACTION_RUN_CLEAN_JOB', 'CLEAN_DATABASE_ACTION', 'ACTION_INSERT_DUMMY_DATA', 'YES_ACTION', 'newsapp',
            'WAKE_UP_REQUESTED', 'caucuses', 'SUBSCRIBE', 'RemoteService', 'ArticleActivity', 'SavedArticleActivity', 'intent_init', 'APP_MARKET',
            'ACTION_CD0F993A', 'ACTION_54DDCDB7', 'ACTION_CD890B4F', 'ACTION_66E27B08', 'ACTION_WIDGET_UPDATE', 'action_notify_clicked', 'SOFT_RESET.1',
            'official', 'areader', 'DOWNLOAD_TIMEOUT', 'Smart', 'INBOX_NOTIFICATIONS', 'vent', 'NAVIGATE', 'story', 'ACTION_GAMOOGA_CHAT', 'EXIT_NOTIFICATION',
            'ACCEPT_FRIEND', 'WIDGET', 'avos', 'PUSH_BIND', 'PUSH_AVOS_REG', 'PUSH_AVOS_UNREG', 'fire_notification', 'SUPPORT4_SAMPLE_CODE', 'mobil',
            'ACTION_DOWNLOAD_START', 'ACTION_DOWNLOAD_CANCEL', 'viewer', 'DISPLAYED', 'CLOSED', 'YOUR_ACTION', 'START_BLURAY_SERVICE',
            'theme_activate_launcher', 'GET_RESOURCES', 'ikeyboard', 'TREBLESHOT_SEND_TEXT', 'TREBLESHOT_SEND', 'TREBLESHOT_SEND_MULTIPLE',
            'UPDATE_STORAGE_PATH', 'ADD_IP', 'bfly', 'SET_WALLPAPER2', 'beautiful', 'her', 'SEND_AS_MESSAGE', 'IsManagedAppFlag', 'BrowserLiteCallback',
            'KEYBOARD_THEME', 'CONFIG_ANALOG', 'SET_THEME_RESPONSE', 'SYNC_SETTINGS', 'carmella', 'UserPreferences', 'QUERY_THEME', 'talpabackstage',
            'TIMEZONE_CHANGED ', 'TransitMapViewerActivity', 'RoutePlannerActivity', 'TransitMapListActivity', 'TransitMapCatalogActivity',
            'TransitStationsListActivity', 'TransitDeparturesListActivity', 'TransitDepartureStopListActivity', 'LiveWebViewActivity', 'TariffPlanListActivity',
            'ACTION_MESSAGE', 'ACTION_LIKE', 'ACTION_INTERCEPT', 'REPLACE', 'appmobilemotorista', 'ACTION_LAUNCH_SIMPLE_WEB_VIEW', 'viamichelinmobile', 'askfm',
            'STARTUP', 'list', 'faceshow', 'ACTION_PREFERENCE_ABOUT_SPONSOR', 'battery', 'FAQ', 'twisters', 'PLACESACTIVITY', 'CHATACTIVITY', 'iliga',
            'NativeActivity', 'sport', 'TorneiActivity', 'SubscriptionsActivity', 'gameday', 'clicked', 'one', 'ace', 'INTENT', 'APP_LAUNCHED', '12',
            'FCCLAUNCHER', 'CONTROL', 'INTERNAL_VIEW', 'FACEBOOK_LOGIN', 'albumPhoto', 'GOOGLE_ACCOUNT_CHANGE', 'PING', 'APP_OOBE_COMPLETED',
            'SHEALTH_ACCOUNT_SIGNOUT_COMPLETED', 'SERVER_SYNC_UPDATED', 'CONNECTION_STATUS_CHANGE', 'MY_PACKAGE_REMOTE_STARTED', 'WEARABLE_SYNC_DONE',
            'DATA_DELETED', 'DEVELOPMENT_PREFERENCE', 'gp', 'ACTION_APPWIDGET_OPTIONS_CHANGED', 'TOGGLE_PLAY_ACTION_EQ', 'STOP_ACTION_EQ',
            'GEOFENCE_NOTIFICATIONS', 'BEACON_NOTIFICATIONS', 'hiyo', 'forceUpdateWidget', 'V2', 'RECOGNIZE_SPEECH', 'xhs', 'ACTION_ICC_COMMAND', 'SHOW_ALARMS',
            'REFRESH_STATE', 'classic', 'ACTION_SHOW_DETAIL', 'ACTION_TIME', 'pad', 'aolapp', 'AUDIO_COMPLETE', 'ideas', 'common', 'TBLO2',
            'ACTION_DEVICE_DISCONNECTED', 'GETWAY', 'donahuere', 'smarteye', 'destroy', 'onlineforextrading', 'lindawelshrealty', 'moblie_grooming', 'rockwell',
            'rogroup', 'ragmb', 'SYNC_COMPLETED', 'research', 'SHOW_NEW', 'howardhannare', 'androidtest', 'bhhsco', 'paybills', 'STOCK_LIST_CHANGED',
            'MARKET_LIST_CHANGED', 'FUND_LIST_CHANGED', 'ETF_LIST_CHANGED', 'CURRENCY_LIST_CHANGED', 'BTP_LIST_CHANGED', 'FUTURE_LIST_CHANGED',
            'APPWIGET_ENABLED', 'QUOTES_UPDATING', 'QUOTES_UPDATED', 'WIDGET_CONFIG_CHANGED', 'org', 'grip', 'ACTION_SEEK', 'POSITION', 'exchange', 'CHECK',
            'TimeService', 'CAPTUREPHOTO', 'CHANGE_AUTO_UPDATE_PERIOD', 'down', 'START_FTPSERVER', 'STOP_FTPSERVER', 'ACTION_PACKAGE_FULLY_REMOVED',
            'newspapers', 'galade', 'malayalamsamayam', 'push_notification', 'REFRESH_ACTION', 'hd', 'GET_PICTURE_SOURCE', 'LazyPickService', 'WidgetUpdate',
            'appce', 'ACTION_WIDGET_DATA', 'meradio', 'la', 'frames', 'caminteresse', 'INTENT_ACTION_TASKS_REFRESHED', 'InnerWebLanding', 'id3144',
            'ACTION_CELL_ZERO_REFRESH', 'ACTION_CELL_ONE_REFRESH', 'ACTION_CELL_TWO_REFRESH', 'ACTION_CELL_THREE_REFRESH', 'ACTION_CELL_FOUR_REFRESH',
            'ACTION_CELL_FIVE_REFRESH', 'ACTION_CELL_SIX_REFRESH', 'ACTION_CELL_SEVEN_REFRESH', 'ACTION_CELL_EIGHT_REFRESH', 'ACTION_CELL_NINE_REFRESH',
            'ACTION_CELL_TEN_REFRESH', 'ACTION_CELL_ELEVEN_REFRESH', 'ACTION_CELL_TWELVE_REFRESH', 'ACTION_CELL_THIRTEEN_REFRESH',
            'ACTION_CELL_FOURTEEN_REFRESH', 'ACTION_CELL_FIFTEEN_REFRESH', 'ACTION_CELL_SIXTEEN_REFRESH', 'ACTION_CELL_SEVENTEEN_REFRESH',
            'ACTION_CELL_EIGHTEEN_REFRESH', 'ACTION_CELL_NINETEEN_REFRESH', 'ACTION_CELL_TWENTY_REFRESH', 'ACTION_CELL_TWENTY_ONE_REFRESH',
            'ACTION_CELL_TWENTY_TWO_REFRESH', 'ACTION_CELL_TWENTY_THREE_REFRESH', 'ACTION_CELL_TWENTY_FOUR_REFRESH', 'ACTION_CELL_TWENTY_FIVE_REFRESH',
            'ACTION_CELL_TWENTY_SIX_REFRESH', 'ACTION_CELL_TWENTY_SEVEN_REFRESH', 'ACTION_CELL_TWENTY_EIGHT_REFRESH', 'ACTION_CELL_TWENTY_NINE_REFRESH',
            'ACTION_CELL_THIRTY_REFRESH', 'ACTION_CELL_THIRTY_ONE_REFRESH', 'ACTION_CELL_THIRTY_TWO_REFRESH', 'ACTION_CELL_THIRTY_THREE_REFRESH',
            'ACTION_CELL_THIRTY_FOUR_REFRESH', 'ACTION_CELL_THIRTY_FIVE_REFRESH', 'ACTION_CELL_THIRTY_SIX_REFRESH', 'ACTION_CELL_THIRTY_SEVEN_REFRESH',
            'ACTION_CELL_THIRTY_EIGHT_REFRESH', 'ACTION_CELL_THIRTY_NINE_REFRESH', 'ACTION_CELL_FOURTY_REFRESH', 'ACTION_CELL_FOURTY_ONE_REFRESH',
            'FIRST_DAY_OF_WEEK_CHANGED', 'ACTION_MOVE_TO_PREV', 'ACTION_MOVE_TO_NEXT', 'ACTION_MOVE_TO_TODAY', 'PREMIUM_VERSION_PURCHASED', 'tres24', 'grid',
            'myidea', 'txsmart', 'WidgetThumbnailUpdate', 'ReleasePlayerUpdate', 'CLIENT_PUSH_RECEIVE', 'tamilsamayam', 'system', 'pgachamp2013', 'KILL',
            'SHOW_FORECAST', 'TIMER_ACTION', 'IPluginFunctions', 'PluginService', 'ON_INSTALL_SCAN_PROGRESS', 'ON_INSTALL_SCAN_RESULT',
            'ACTION_APPLOCK_PIN_UPDATE', 'ActionStatusUpdated', 'ON_MOUNT_SCAN_PROGRESS', 'ON_MOUNT_SCAN_RESULT', 'FETCH_REMOTE_CONFIG', 'START_FLOW',
            'STOP_FLOW', 'delay', 'LockService', 'mobilesecurity', 'mydatachange', 'allchange', 'taskinfochange', 'eventinfochange', 'pnp', 'fosse', 'SOFIRE',
            'apricot', 'ACTION_SEND', 'icruise', 'ACTION_CV', 'cupshe', 'travel', '35032', 'VISION_WIDGET_UPDATE_42', 'VISION_WIDGET_UPDATE_22',
            'VISION_WIDGET_UPDATE_11', 'EXECUTE_ACTION', 'finish_activity', 'lookout', 'CLEARED_NOTIFICATION', 'interracial', 'Menu', 'cheaptickets',
            'slideplus', 'REQUEST_VALUE', 'RECEIVE_VALUE', 'notification_discarded', 'netviewtech', 'slots', 'philadelphia', 'GAReceiver', 'ACTION_DAY_CHANGED',
            'ACTION_WIDGET_IMAGE_READY', 'ACTION_WEATHER_UPDATED', 'ACTION_WEATHER_FORECAST_CHANGED', 'ACTION_WEATHER_ALERT_CHANGED', 'ACTION_LOCATION_REMOVED',
            'ACTION_AUTO_REFRESH_RATE_CHANGED', 'ACTION_ALL_LOCATION_LOADED', 'ACTION_LOCATION_LOADED', 'APP_LOCALE_CHANGED', 'SHOURD_UPDATE',
            'AUTOUPDATE_WEATHER', 'REQUEST_WIDGET_BACKGROUND', 'INTENT_FIRST_START', 'ROTATE_CITY', 'NETATMO_RECONFIGURE', 'NETATMO_UPDATE_SINGLE',
            'NETATMO_RESET_WIDGET', 'NETATMO_RESPONSE_UPDATE_WITH_DATA', 'FEATURE', 'FORWARD_AS_ORDERED_BROADCAST', 'puzzle', 'wordsearch', 'hh', 'legendary',
            'cookiecollector2', 'IF', 'FREE_LOTTERY', 'TYPE', 'DURATION', 'LOCATION.2', 'NUMBER', 'FEATURES', 'DATE', 'requestLocationUpdates', 'authenticate',
            'getSignature', 'getOriginalJson', 'vnd.android.cursor.item/name', 'vnd.android.cursor.item/organization', 'vnd.android.cursor.item/email_v2',
            'vnd.android.cursor.item/im', 'vnd.android.cursor.dir/contact', 'DATA_USAGE', 'vnd.android.cursor.item/group_membership', 'content://sms/sent',
            'vnd.android.cursor.item/contact', 'vnd.android.cursor.dir/email_v2', 'content://sms/inbox', 'takePicture', 'COUNTRY_ISO',
            'vnd.android.cursor.item/vnd.com.whatsapp.profile', 'vnd.android.cursor.dir', 'CONTENT_URI', 'vnd.android.cursor.dir/calls',
            'vnd.android.cursor.item', 'content://sms/draft', 'GEOCODED_LOCATION', 'VIA_NUMBER', 'VOICEMAIL_URI',
            'vnd.android.cursor.item/vnd.com.viber.voip.viber_number_message', 'vnd.android.cursor.item/calls',
            'vnd.android.cursor.item/vnd.com.linkedin.android.profile', 'getAudioSessionId', 'getOfferSessionDescription', 'getCallId', 'getLine1Number',
            'getExternalStorageDirectory', 'getUserData', 'getScanResults', 'getNetworkInfo', 'OUTGOING_TYPE', 'CACHED_NAME',
            'vnd.android.cursor.item/vnd.googleplus.profile', 'PHONE_ACCOUNT_COMPONENT_NAME', 'PHONE_ACCOUNT_ID', 'INCOMING_TYPE',
            'vnd.android.cursor.item/vnd.facebook.profile', 'getInstance', 'baseUrl', 'build', 'getName', 'protocols', 'readTimeoutMillis', 'cache',
            'authenticator', 'dispatcher', 'proxy', 'proxySelector', 'connectionPool', 'dns', 'socketFactory', 'callTimeoutMillis', 'certificatePinner',
            'interceptors', 'writeTimeoutMillis', 'newRequestQueue', 'add.1', 'getOptions', 'initializeApp', 'pii', 'icp']

print(len(features))
ar = reconstructed_model.predict(tryClass)
print(ar[0])
